### ISSUE TITLE
Replace run_experiment with a decorator

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#1049]
@krzentner will furnish more details on the design here

**Comment by krzentner** [comment]
We have a large number of requirements we would like our experiment interface to have:
 - It should naturally capture what we think of as an "experiment" - it should have a name, parameters, and manage the life cycle of related objects. In python, the natural way of specifying a "thing with parameters" is a function. Functions are also fairly natural ways of specifying life cycles, and have names.
 - It should be very natural to invoke an experiment with unique parameters.
 - The parameters of an experiment should be saved, and invoking the same experiment with different parameters should result in different log directories.
 - It should be possible to run the experiment from the current process, since sub-processes add significant complexity to development and debugging.
 - The contents of a log directory should be predictable (in other words, all experiment directories should have their sub-files in the same locations).
 - It should be very easy to add command-line parameters, and they should be properly handled as experiment parameters (i.e. saved in `variant.json`).
 - The implementation should not be particular about how command-line argument handling is performed.
 - The implementation should also not be particular about how experiments are distributed across computers.

Essentially, these constraints imply that we want experiments to act in the following ways:
 - They should be callable with their parameters, like normal functions.
 - They should create unique log directories based on those parameters.
 - They should also have access to critical experiment information (at least what's currently contained in the `SnapshotConfig`).

The most natural way to fulfill these requirements is as a decorator which turns a function into an `Experiment` (or perhaps `ExperimentTemplate`).

It would be used something like this:
```python
from garage.experiment import experiment

...

@experiment
def car_trpo(ctxt, max_kl_step=0.01):
    runner = LocalTFRunner(ctxt)
    ...
    runner.train(...)

for max_kl_step in [0.001, 0.01, 0.1]:
    # Produces three experiment directories, car_trpo_1, car_trpo_2, and car_trpo_3
    car_goal_mt_trpo(max_kl_step)
```

Or:
```python
import clize  # Add command line arguments
from garage.experiment import experiment

...

# Produces a new experiment directory each time it's invoked.
@clize.run
@experiment(prefix='remote', dry=True)
def car_trpo(ctxt, max_kl_step=0.01):
    runner = LocalTFRunner(ctxt)
    ...
    runner.train(...)
```

**Comment by ryanjulian** [comment]
this looks great

some people like to name their experiment directories with their hyperparams (because tensorboard support is so poor for this). we might be able to add an option to slugify a summary of the hyperparams and use it as a post-fix on the name.

e.g. from the example

```python
from garage.experiment import experiment

...

@experiment(slugify_hparams=True)
def car_trpo(ctxt, max_kl_step=0.01):
    runner = LocalTFRunner(ctxt)
    ...
    runner.train(...)

for max_kl_step in [0.001, 0.01, 0.1]:
    # Produces three experiment directories, car_trpo_max_kl_step_1e-3, car_trpo_max_kl_step_1e-2, and car_trpo_max_kl_step_1e-1
    car_goal_mt_trpo(max_kl_step)
```

**Comment by krzentner** [comment]
This exists now. I don't think we're going to delete `run_experiment` this version.
