### ISSUE TITLE
Cloudpickle version issue?

### ISSUE THREAD

**Issue by Maltimore** [rlworkgroup/garage#1067]
I tried to install garage into a clean conda environment (in fact, I tried three separte clean envs, once with python 3.5, 3.6 and 3.7, same results everywhere).

Then the only thing I do is "pip install garage". It downloads a bunch of packages but in the end I get:

> ERROR: tensorflow-probability 0.8.0 has requirement cloudpickle==1.1.1, but you'll have cloudpickle 1.2.2 which is incompatible.

I used pipdeptree to see which packages depended on cloudpickle, and it seemed to be only garage and tensorflow-probability: 

[pipdeptree_output.txt](https://github.com/rlworkgroup/garage/files/3879419/pipdeptree_output.txt)

I don't really understand why pip isn't just installing cloudpickle 1.1.1 as required by tensorflow-probability, since garage seems to have no restriction on the cloudpickle version. Maybe this is a pip issue instead?

**Comment by ryanjulian** [comment]
pip doesn't doesn't solve for a stable set of dependencies. To get that feature, you need to use pipenv, conda, or poetry.

Which operating system are you using? I have seen this make uninstalls on pipenv+MacOS unsuccessful.

**Comment by Maltimore** [comment]
> pip doesn't doesn't solve for a stable set of dependencies. To get that feature, you need to use pipenv, conda, or poetry.

I tried using conda with 

`conda install garage`

but there's no garage package on conda.

Also, the recommended way to install garage via conda (https://garage.readthedocs.io/en/latest/user/installation.html) is:

`conda activate myenv
pip install garage`

but that's when above described error occurs.

>Which operating system are you using? I have seen this make uninstalls on pipenv+MacOS unsuccessful.

I'm using ubuntu 18.04.

**Comment by ryanjulian** [comment]
@Maltimore you're correct, there is no conda-native package for garage. If you'd like to see one, you can track #1042 or contribute a package yourself. I'm happy to code review for it.

Note that the latest release of garage on pip (v2019.10.0) has a few bugs. We will release a maintenance release (v2019.10.1) at the end of this month. You can track the flaws that have been fixed by looking at [GitHub's summary](https://github.com/rlworkgroup/garage/compare/v2019.10.0...release-2019.10) of the changes since the release.

Note that the "ERROR" about `cloudpickle` doesn't prevent garage from working, at least in my experience so far. Messages like this are typical of using pip with larger projects and the number of solutions we can offer is limited because of how Python package management works. The root cause is `tensorflow-probability` setting a too-restrictive requirement on `cloudpickle`. It has been corrected in their master branch [here](https://github.com/tensorflow/probability/commit/78ef12b5afe3f567d16c70b74015ed1ddff1b0c8#diff-2eeaed663bd0d25b7e608891384b7298), but will not appear in garage until they make a new release.

If this is stopping your installation from working, you can download the `garage` repo and edit `setup.py` to have the requirement `cloudpickle==1.1.1`. You can then install garage using the [developer installation instructions](https://garage.readthedocs.io/en/latest/user/installation.html#extra-steps-for-developers). If this flaw is causing your garage installation to now work (other than nasty messages on the terminal), we can make a PR to pin the version until tensorflow-probability fixes it on their end.

Please let us know what happens. If we don't hear from you in a few days, I'll assume everything is fine and close the issue.

**Comment by Maltimore** [comment]
Thanks for the extended answer!

I think there are several possible workarounds for this, for instance I solved it by manually installing cloudpickle==1.1.1 manually and afterwards installing garage with pip. It worked and gave no error messages.

The reason I created the issue was only to point out that this should still be fixed, didn't know it was on the radar.
