### ISSUE TITLE
Having the option to disable pytest-xdist locally

### ISSUE THREAD

**Issue by avnishn** [rlworkgroup/garage#1112]
Currently, pytest-xdist for parallel testing makes it hard to debug tests in garage using pdb. I find that by removing the `-n auto` from `setup.cfg` I am able to use pdb, however instead of removing this line, I'd rather that we had a flag available to us so we can disable the -n auto flag in the setup.cfg for when we are debugging tests.

@gitanshu does this feature already exist? And if not, is it possible for it to be implemented in garage?

**Comment by ryanjulian** [comment]
You always have the chance to turn off pytest-xdist -- just call pytest yourself without the `-n` argument, or just edit `setup.cfg`. Refer to the pytest man page for how to override `setup.cfg` options.

If you are referring to running tests with Docker using the Makefile, well Makefiles don't accept command line arguments, so it's not implementable that way. If you really want, you can create a new target in the Makefile which doesn't use pytest-xdist in its run command. Perhaps what you want is a make target which launches an interactive debug session within your test job?

Since it's not clear what you want here, I'm going to close this issue. If you figure out what dev feature you want locally, feel free to open a PR to add it. I'm sure others would find it useful.
