### ISSUE TITLE
environment difference between garage and rllab

### ISSUE THREAD

**Issue by gaosh** [rlworkgroup/garage#1121]
Hi, I tried to implement [Hessian Aided Policy Gradient](http://proceedings.mlr.press/v97/shen19d.html) with garage and pytorch. When testing my implementation, I found that the average reward from my implementation is completely different from the results of their paper with the CartPole environment. With 100 max step length, they can achieve more than 800, I can achieve at most 100. After I checked their original code, I found that the CartPole environment they used (which is from rllab) is different from the original gym environment. I didn't find similar environments are implemented in the current version of garage. I am not sure how to solve such inconsistency given the current version of garage.

**Comment by ryanjulian** [comment]
Hi @gaosh,

Thanks for opening an issue. A while back, we removed the rllab versions of most environments because most of the community has mostly standardized on the gym implementations of these environments. We didn't want people to confuse these with gym versions, and every line of code makes more maintenance work for an open source project like ours.

I think the last garage release with the CartPole env was `v2018.10.1`. You can find a link to that code [here](https://github.com/rlworkgroup/garage/blob/v2018.10.1/garage/envs/box2d/cartpole_env.py). I think you will find it possible to graft this code your own project for the purposes of establishing a baseline, but I recommend you use the gym versions once you are confident your code replicates the paper.

`v2018.10.1` has no PyTorch support, and the `v2018.10.1` release is no longer supported, so I don't recommend you try basing your project on `v2018.10.1`.

PS: When you finish implementing HAPG, we'd love it if you'd open a PR to add it to garage.

**Comment by ryanjulian** [comment]
@gaosh I will close this for now. Please open a new issue if you need more help!
