### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by MHashemzadeh** [rlworkgroup/garage#1161]
We tried to install garage toolkit on Ubuntu and ran tf and torch examples.I was able to run tf examples successfully, however, I could not run any of torch examples.
I found that many of the functions in torch category are not installed in the package. Actually, I saw that the torch examples could not import many of the function and then I found that these are not added to the __init__.py in the package install directory (home/user/anaconda3/envs/env7/lib/python3.7/site-packages/garage). Afterwards, I added them manually to that directory. then I found that it is not the right way because resulting in many other types of errors like the following screenshot: 

![image](https://user-images.githubusercontent.com/19494676/74078596-ab65bb00-49e9-11ea-8613-3f057fa5acc4.png)

**Comment by ryanjulian** [comment]
Hi @MHashemzadeh -- thanks for filing an issue.

Are you installing garage from Github or from pip?

Note the error on the last line -- it appears you are trying to use a module which requires MuJoCo. In that case you will need to follow the MuJoCo installation instructions (or use the scripts in scripts/) to help install dependencies, and then install the optional package `garage[mujoco]`. We keep a separate variant because not everyone has a MuJoCo license.

Another option is to run your code using the provided Dockerfiles, which can be accessed easily using the Makefile (type `make` in the repository root for help, or read the `Makefile`).

Note that if you are installing from `pip`, some features visible on the GitHub will not be available, because we only release the software 3 times per year, in an effort to keep it stable. The next release is scheduled for the end of this month, but may be delayed. The torch features are very new, and some of them don't appear in the `pip` package. You can get around this by installing a pre-release version. The latest pre-release is `2020.2.0rc1` but I just cut another one `2020.02.0rc2` for your convenience, which has the latest code on GitHub up to today.

Please let me know if you have further trouble -- I'll close this issue but feel free to reopen it.

**Comment by MHashemzadeh** [comment]
Hi @ryanjulian 
Thanks a lot :) . Your comment solved my issue. 
I also was wondering if you insert MAESN algorithm to "garage"? Or do you have a plan to add it to the package?
Thanks

**Comment by ryanjulian** [comment]
We'd like to add MAESN but don't have specific plans for when yet.

As you can see from recent commits and PRs, we have been working hard on adding meta- and multi-task RL support. We're focusing on getting our meta-/MTRL support solid with the first several algorithms before adding a lot of new ones to the library.

Once the basics for that are in place, adding MAESN should not be super hard. I'd love a pull request for it :).
