### ISSUE TITLE
Remove gym dependency

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#1276]

**Comment by haydenshively** [comment]
Installing garage dependencies into a fresh conda environment (Python 3.8) via `pip install --no-cache -e ."[mujoco,dm_control]"` yields the following errors related to gym:

`ERROR: gym 0.15.4 has requirement cloudpickle~=1.2.0, but you have cloudpickle 1.4.1 which is incompatible.`
`ERROR: gym 0.15.4 has requirement pyglet<=1.3.2,>=1.2.0, but you have pyglet 1.3.3 which is incompatible.`

**Comment by ryanjulian** [comment]
Thanks for the report! We're aware of these problems but thankfully it doesn't affect functionality and they can be safely ignored.

Narrow dependency specifications is one of the reasons we're trying to remove this dep.

**Comment by ryanjulian** [comment]
@haydenshively since you assigned yourself to this, can you provide us with a blueprint for your plan?

**Comment by haydenshively** [comment]
Outside of `garage.envs` and tests, there are only a handful of uses of `gym`.

- `AddGaussianNoise` in the `np` folder: checks that the action space is an instance of `gym.spaces.Box`
- `Plotter`: at least according to the docstring, this assumes that the `env` passed in is a `gym.Env`
- `TransposeImage` in `_functions.py`: extends `gym.ObservationWrapper` and sets the action space to a `gym.spaces.Box`

I'm currently under the impression that removing these usages will be sufficient to close this issue. If that's incorrect please let me know.

As for how to remove them... I believe the `Plotter` docstring is simply wrong, but I can double check. The `gym.spaces.Box` types should be replaced with `akro.Space`, and `TransposeImage` should implement our environment `Wrapper` rather than `gym.ObservationWrapper`
