### ISSUE TITLE
Add capability of saving non-serializable environment

### ISSUE THREAD

**Issue by parachutel** [rlworkgroup/garage#1285]
Some `gym` environments like Google Research Football are not serializiable, which will cause problem when saving env through `param['env']` in `LocalRunner.save()`, where param is to be serialized by snapshotter. I would suggest adding options for saving environment creating functions to bypass this problem.

**Comment by ryanjulian** [comment]
Hi @parachutel 

Thanks for trying garage!

We use the pickling protocol (instead of functors, for example), because it is defined by Python itself and therefore standard across implementations. The `pickle` library in the Python standard library can't even pickle anonymous functions (though `cloudpickle`, which we use, can). Generally, we follow the Python commnunity ethos that if the standard library already provides a sufficient API for what we want to do, we'd rather use that API definition rather than invent a new API.

We also notably avoid the use of functors (anonymous function arguments) which, though popular in some RL libraries, can lead to very difficult-to-discover APIs for users.

When we come across an environment which is not pickleable, our standard solution is to implement a wrapper which implements the pickle protocol for that environment (i.e. `__get_state__` and `__set_state__`). 

No promises this code runs, but looking at the Google Research Football code, it could be as simple as below. They seem to have implemented all of the logic required for the pickle protocol, but stopped short of exporting them as `__get_state__` and `__set_state__`, which would allow Python to serialize the env automatically. 

If you find out whether this runs or not, let us know and we can add it to `garage.envs` (or send a PR yourself!)

```python
class GoogleResearchFootballEnv(gym.Wrapper):
    """Makes Google Research Football environments pickleable."""

    def __get_state__(self):
       return self.env.get_state()

    def __set_state__(self, state):
        self.env.set_state(state)
```

**Comment by parachutel** [comment]
Hi @ryanjulian 

Thanks for your quick response! 

The major reason the FootballEnv is not pickleable is because it has an attribute `FootballEnv._config` which is of type `_gameplayfootball.GameConfig`. The `_gameplayfootball` is coded with C++ and compiled into a shared object file, instead of Python.

**Comment by ryanjulian** [comment]
@parachutel have you tried the fix I suggested? AFAICT my fix should avoid this very problem.

**Comment by parachutel** [comment]
@ryanjulian Yeah, I tried, and the problem still exists.

**Comment by ryanjulian** [comment]
@parachutel can you post a stacktrace/error message of the failure to serialize?

**Comment by ryanjulian** [comment]
Hey @parachutel -- in case you copied my code exactly, someone pointed out that I added an extra _ to the method names -- see updated example below.

```python
class GoogleResearchFootballEnv(gym.Wrapper):
    """Makes Google Research Football environments pickleable."""

    def __getstate__(self):
       return self.env.get_state()

    def __setstate__(self, state):
        self.env.set_state(state)
```

**Comment by parachutel** [comment]
Hey @ryanjulian, the updated code solved problem perfectly. Thanks a lot for the help and actively developing this amazing RL library!

**Comment by ryanjulian** [comment]
@parachutel Would you be interested in contributing a PR with you wrapper? If not, I'll add it to our backlog.

**Comment by parachutel** [comment]
@ryanjulian Sure! I'll do it as soon as I got the time.
