### ISSUE TITLE
RaySampler does not use all workers

### ISSUE THREAD

**Issue by gagankhandate** [rlworkgroup/garage#1349]
In release 2019.10, [RaySampler](https://github.com/rlworkgroup/garage/blob/release-2019.10/src/garage/sampler/ray_sampler.py) sees only one of the workers as idle for all iterations after the first iteration. This can be seen with [examples/tf/trpo_swimmer_ray_sampler.py](https://github.com/rlworkgroup/garage/blob/release-2019.10/examples/tf/trpo_swimmer_ray_sampler.py). 

To me it looks like `self._idle_worker_ids` is not correctly updated at the end of `obtain_samples()` [here](https://github.com/rlworkgroup/garage/blob/d6c993526c23c289ebc94635a78186d9bf197f32/src/garage/sampler/ray_sampler.py#L130). Only those workers which have returned with a result are put back in the idle pool. This is a problem because results from some workers are not processed at the end and these workers don't go back into the idle pool. 

A quick fix (?) is to reset the list of idle workers ids to all workers ids at the start of `obtain samples()`. This does result in all the workers being used for all iterations. Since the agent parameters are updated in the next iteration, the samples from the previously not ready workers must be valid. However, I am not totally sure. 

@avnishn @ryanjulian Appreciate it if the fix can be back-ported to 2019.10!

**Comment by krzentner** [comment]
Hi Gagan,

Thanks for the bug report. We'll definitely look into why it's not using all workers.
Unfortunately, it doesn't look like your explanation why it's happening is quite right.
In particular, workers are still added to `self._idle_worker_ids` [here](https://github.com/rlworkgroup/garage/blob/d6c993526c23c289ebc94635a78186d9bf197f32/src/garage/sampler/ray_sampler.py#L163) (which was a super confusing location for it to happen, hence why it was refactored out since then). There's probably some other reason not all of the workers are being utilized fully, but it's not clear to me what it is.

**Comment by gagankhandate** [comment]
Yes, I did see that `self._process_trajectory()` updates the list of idle workers but this is called only in the while loop which exits after collecting enough samples. At this stage we have some workers for which we have not called _process_trajectory() on their results. These workers don't go back into the idle pool because processing the results is the only place where `self._idle_worker_ids` are repopulated. Just to re-iterate, I think the issue is in the last iteration of the while loop to collect samples.

**Comment by ryanjulian** [comment]
@krzentner do you need any more information from @gagankhandate for this issue? Can you help triage (it i.e. is this a bug or not?)

**Comment by ryanjulian** [comment]
@krzentner bump!

**Comment by avnishn** [comment]
@ryanjulian I thought we created the fix for this. Is there still an issue?
