### ISSUE TITLE
What is the best way to install garage?

### ISSUE THREAD

**Issue by sereysethy** [rlworkgroup/garage#1360]
Hello,

I ran into problems of installation of garage. I tried pip install garage, but I think it is not recommended as the package is not up to date. I also tried to use docker, but docker is not a way to use it to develop applications.

I checked in the closed/opened issues, I saw that there is a new documentation that will be out in June. But in the mean time, my question is what is the best way to install garage so that I can use it in my project?

Thanks.

**Comment by ryanjulian** [comment]
Hi @sereysethy 

Thanks for your interest in garage, and for thoroughly reviewing the issues before making a new one. **I cut a new pre-release (`v2020.04rc1`) for you this morning. It has everything on `master` as of your issue. You should be able to install it using `pip install garage==2020.4.0rc1`.**

Prior to this, you could also install `2020.2.0rc1` and `2020.2.0rc2`. For available releases and pre-releases, you can always check [our PyPI page](https://pypi.org/project/garage/#history) or our [GitHub releases page](https://github.com/rlworkgroup/garage/releases).

The best way to install garage is always with pip. The latest release is `v2019.10` which was released in October. The primary differences between `v2019.10` and `master` are (1) more PyTorch algorithms and (2) Meta- and multi-task RL support. If you don't need either of those things, installing `v2019.10` via pip should be just fine.

We also periodically post pre-releases on pip, for people who have more appetite for instability.

**Comment by sereysethy** [comment]
Thank you for your prompt reply.

I would like to report some findings when I did installations on Linux and Mac OS.

I have installed the new version per your advise **`pip install garage==2020.4.0rc1`**, I think it has some problems of dependencies or it has problems with python version on Linux `Python 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0] on linux`.

```
ERROR: gym 0.15.4 has requirement cloudpickle~=1.2.0, but you'll have cloudpickle 1.4.1 which is incompatible.
ERROR: gym 0.15.4 has requirement pyglet<=1.3.2,>=1.2.0, but you'll have pyglet 1.3.3 which is incompatible.
ERROR: torchvision 0.6.0 has requirement torch==1.5.0, but you'll have torch 1.4.0 which is incompatible.
```

I also installed the `v2010.10` on Linux with Python 3.6.9, but it fails to run the examples`trpo_cartpole.py`. I got this error `Illegal instruction (core dumped)`. The same thing happened for the new version `2020.4.0rc1`.

Also for the docker version, I got the same error `Illegal instruction (core dumped)`

But when I installed it on Mac with Python 3.7.4

```
Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
```
I was able to run the example of `trpo_cartpole.py`.

Actually I am new to garage and to be honest I dont know where to start.

My purpose is to use RL algorithm as a learning algorithm in my research work. I want to do a simple thing first (function approximation using linear function for example) to use it as a baseline before I dive deep into a more complex algorithm using a more complex feature.

Is there any examples that I can follow to get myself familiar with garage concept? The example in the documentation of `Implementing New Environments` is outdated. I checked in the issues, it seems I have to wrap env in tf env, etc.. but can you point me to an example where I can follow it step by step to see how garage works? or everything is in the examples folders and I have to dig deeper? I am more interested in using Pytorch as my ML framework.

**Comment by ryanjulian** [comment]
You can feel free to ignore the dependency errors, as they are harmless. Gym is unnecessarily-strict with some dependencies and this makes it difficult to work with. #1359 will fix the error about torchvision, though this is also harmless.

I would need more info on your Docker setup to help. You can try `make test` on your machine (you need docker-compose installed) running docker to verify the container is running correctly. We run this container on every build, so it's unlikely it's broken. `make test` could take hours to finish on some machines, so I don't recommend letting it finish :). `make run-headless RUN_CMD="python path/to/my/script.py"` will allow you to run an arbitrary script inside the docker container.

I apologize that the Getting Started documentation is quite out-of-date. This is an item we are working on for the June release. My best advice for seeing how garage works now is to look at the `examples/` folder in the repository and, if you're curious about something, read the source code (which is usually pretty well-documented). 

Note that for PyTorch, you wrap with GarageEnv rather than TfEnv. You can see exactly what to do in the examples.

If you give us an idea of what you are trying to achieve (run existing algorithm/environment, train an algorithm on your own environment, add an algorithm, add a new architecture to an existing algorithm, etc.) we can help with better pointers for where to start.

**Comment by sereysethy** [comment]
Thank you.

I will try to run the example and try to understand it. My idea is to develop my own environment for my work. My primary research is not really focused on RL but rather than applying RL techniques to solve my problem. But to get started I need to understand how garage work, so that I can integrate it to my research work and do some off-line and on-line experimentation.

Another question is that are there any use cases of Garage library in real applications?

**Comment by ryanjulian** [comment]
If you desire is primarily to design and environment and try to optimize that environment with RL, I think you will have a fairly easy  time. Essentially, you only need to ensure your environment complies with the `gym.Env` interface and, in the case of `garage.torch`, wrap your environment with `garage.envs.GarageEnv` before passing it to an algorithm. 

garage is typically used by RL researchers in academia, rather than in industry.

That's not to say it couldn't be -- we design garage carefully to follow standards of design, reusability, testability, and maintainability which are much more common in large industry codebases than in research libraries.

I'm honestly not aware of any open source RL library known to be in use for an industrial application. The few companies creating industrial applications where RL is currently being used (likely in high-frequency trading/finance, programmatic ads (e.g. Facebook and Google), video games, perhaps a couple new robotics start-ups) consider their code to be closely-guarded trade secret.
