### ISSUE TITLE
Garage pip3 installation error

### ISSUE THREAD

**Issue by zengyizhe** [rlworkgroup/garage#1421]
I was trying to install garage by "pip3 install garage", however, here is a error. 

ERROR: Could not find a version that satisfies the requirement tensorflow<1.16,>=1.15.0 (from garage) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0)
ERROR: No matching distribution found for tensorflow<1.16,>=1.15.0 (from garage)

How could I solve it?

Ubuntu 20.04 LTS
Tensorflow-gpu 2.2.0
Python 3.8.2

**Comment by ryanjulian** [comment]
Hi @zengyizhe -- thanks for trying garage

First, we always recommend you install garage using an environment manager (virtualenv, conda, pipenv, poetry, etc.) to avoid conflicts with system Python dependencies and among projects. A Python library of garage's size is bound to create conflicts with pre-installed software.

garage 2019.10 (the version currently-available on pip/PyPI) is not compatible with TensorFlow 2, so you won't be able to install `v2019.10` in an Python environment which uses TensorFlow 2.

The next release of garage (v2019.05) will use the TensorFlow 2 library, but doesn't use any of the TF2-specific features (e.g. eager mode, @tf.function, etc.). If you need to install garage in an environment which otherwise requires tf2, or just want the latest possible version, you can 
1) [Install the latest pre-release from PyPI](https://pypi.org/project/garage/#history) (i.e. `pip3 install garage==2020.05.0rc1`) or 
2) Install garage from source, e.g. `git clone https://github.com/rlworkgroup/garage.git && pip3 install garage/`

You can find better documentation of the installation process on [our ReadTheDocs page](https://garage.readthedocs.io/en/latest/user/installation.html#install-garage-in-a-python-environment).
