### ISSUE TITLE
Some Questions About Latest Stable API

### ISSUE THREAD

**Issue by DarrenRuan** [rlworkgroup/garage#1514]
Hi, I just noticed that there have been lots of changes in APIs, e.g., `Remove garage.tf.envs.TfEnv (#1443)` and `Remove tf batchpolopt (#1504)`. Because I just moved from rllab to garage, it might take me some time to pick up the changes. I am wondering do we have a doc about how to change from rllab to garage? Or do we have a doc about the changes and reasons for changes about garage in terms of rllab?

Besides, if I want to use the newer versions of garage but do not want to change lots of codes, like it is fine for me to remove`Serializable`, but I should be able to inherit from tf `TRPO` successfully. Could you suggest which version should I use? `v2020.05rc1` or `garage 2019.10.1`?

**Comment by ryanjulian** [comment]
Hi @DarrenRuan 

Thanks for trying Garage!

If you are migrating from rllab, you will likely have to change a substantial amount of code, but most of the changes should be very mechanical.

TRPO has been almost completely rewritten since rllab, so it's difficult for me to assess how inheritance would change. You will have to read the code.

I would recommend you start working with `v2020.05rc1` so that you can easily switch to `v2020.06` (the newest release, coming this month) very easily. Alternatively, you can install from GitHub master branch, which is very close to what will become the `v2020.06` release, and wait for the official release in a week or two.

Garage APIs are only guaranteed to be stable within a single YEAR.MONTH release. Our release numbers use the form `vYEAR.MONTH.REVISION`. For instance, there can be arbitrary API changes between `v2019.10.0` and `v2020.06.0`, but `v2019.10.1` contains only bug fixes on top of `v2019.10.0`. We support each release for at least 8 months (with bug fixes), though we recently decided to extend support for `v2019.10` to 12 months, through October 2020.

In practice, when we remove or change a major API, such as replacing `run_experiment` with `wrap_experiment`, we include both APIs in one release, but attach a deprecation warning to the old API to give you notice to switch.
