### ISSUE TITLE
Cartpole Environment, Assertion Error 

### ISSUE THREAD

**Issue by JeremyAlain** [rlworkgroup/garage#1526]
Hi, 
I am new to this framework but really like the whole setup of it. Unfortunately I have spent already quite some time to try and set up the VPG algorithm with the Cartpole Example in torch. Unfortunately I always get an assertion error. I don't know if I am doing something wrong or if it is somehow a bug. So here two ways of reproducing it. I use garage==2020.5rc1

I copy paste this example https://github.com/rlworkgroup/garage/blob/master/examples/torch/vpg_pendulum.py
on line 32 I change 
```
    env = GarageEnv(env_name='InvertedDoublePendulum-v2')
```
with 
```
    env = GarageEnv(env_name="CartPole-v1")
```

I then get the following error, line 92 in step of file gym/envs/classic_control/cartpole.py
assert self.action_space.contains(action), "%r (%s) invalid"%(action, type(action))
AssertionError: array([-0.9646216,  0.7912429], dtype=float32) (<class 'numpy.ndarray'>) invalid

The exact same thing happens when I follow your documentation https://garage.readthedocs.io/en/latest/user/implement_algo.html and copy past the last  code snippet with an implementation of VPG. I again replace the environment to use the CartPole-v1 environment and the exact same thing happens. 

Thanks for your help

**Comment by JeremyAlain** [comment]
Unfortunately if I copy paste the example code in Tensorflow https://github.com/rlworkgroup/garage/blob/master/examples/tf/vpg_cartpole.py I get a completely different error:
 line 124, in __init__
    self._optimizer = optimizer(**optimizer_args)
TypeError: __init__() got an unexpected keyword argument 'learning_rate'

so its somehow a little bit weird that no way of using the cartpole example works.

**Comment by krzentner** [comment]
Hi Jeremy,

Thanks for taking an interest in Garage and filing this issue.
I believe the reason you're encountering this problem is that you're using a `GaussianMLPPolicy`, which outputs actions in a continuous space, with the `CartPole-v1` environment, which expects discrete actions (i.e. left or right).

Unfortunately, we don't have a `CategoricalMLPPolicy` in for PyTorch right now, and it's a little more complicated to write one than I would like. If you want to really dig in, you can.

As for the issue, the way to pass arguments to the optimizer has changed slightly between garage 2020.5rc1 and master. If you use [the example from that release](https://github.com/rlworkgroup/garage/blob/v2020.05rc1/examples/tf/vpg_cartpole.py) it should work.

Please let me know if that doesn't answer your problem!

**Comment by JeremyAlain** [comment]
Hi, 
Thanks so much for your quick reqply. Yes I think you are right and that might explain a lot. I didnt look closely at the details and just assumed it was also a categorical policy, thanks for clearing that up. In that case I might write one myself. 

And thanks also for the other tip.
:)

**Comment by JeremyAlain** [comment]
Sorry just one last question, 
But for the pytorch categoricalmlp policy, couldn't i just use your deterministic_mlp_policy and slightly change it so that it predicts probabilities and sample from them? 

Kind regards Jérémy

**Comment by JeremyAlain** [comment]
Anyway, i tried to change some of the policies you have but without success.  It requires quite a deep understanding of the whole framework and what functions are required etc. to make it work. So i'll just let it go and try the tensorflow VPG with cartpole
