### ISSUE TITLE
Potential Bug: Plotting Cartpole

### ISSUE THREAD

**Issue by JeremyAlain** [rlworkgroup/garage#1550]
I am using garage==2020.5rc1

I am running the code from here https://github.com/rlworkgroup/garage/blob/master/examples/tf/vpg_cartpole.py
and changed the training to 
```
        runner.train(n_epochs=100, batch_size=10000, plot=True, pause_for_plot=True)
```
After the first epoch a quick window with the cartpole example pops up and then closes again. The whole program crashes with the exception 
file garage/tf/policies/categorical_mlp_policy, line 139, in get_action
    sample, prob = self._f_prob(np.expand_dims([observation], 1))
TypeError: 'NoneType' object is not callable

no sure if this is a bug.

**Comment by ahtsan** [comment]
Thank you for your interest in using garage, JeremyAlain! Yes, It is a bug because after the policy is cloned, the network in the policy hasn't been built. We are actively improving the codebase and experiencing rapid changes in the APIs. We backported a fix for tf.plotter but we forgot to also backport a fix for this issue. Again, thank you for bringing this up and I'm sure it would be helpful for other people in the community!

We are submitting a pull request for the above issue, or for a quick fix, you can make the following change in `garage/tf/plotter/plotter.py`:
```
        with self.sess.as_default(), self.graph.as_default():
            self._policy = policy.clone('plotter_policy')
            self._policy.build(policy.model.input) # add this line
```
Please let me know if you have any more questions.

**Comment by ahtsan** [comment]
Please refer to #1554. I'm closing this issue now but feel free to reopen it if you have any more questions!
