### ISSUE TITLE
Pin tensorFlow version again?

### ISSUE THREAD

**Issue by zhanpenghe** [rlworkgroup/garage#1562]
I noticed that tf and tf-probability versions are unpinned. This will actually cause a locking error on `gast` when using `pipenv`. Is there any reason why we don't pin them? I think it could be nice to just pin the version of them.

@Shubham1397-sudo you can probably track this issue and update the deps of our repo later.

**Comment by ryanjulian** [comment]
This is unpinned because it can cause unnecessary locking errors in the other direction, and our code should be compatible with any version of TF >=1.14. We are working towards removing the explicit TF (and PyTorch) deps entirely, so people can use whichever version of TF they like and avoid locking problems. Well, they will still have to solve locking problems in their own projects, but at least garage have an opinion on them.

Given that we don't use any tf2 features, I suppose there's questionable value for us to allow tf2 installs, but locking tf <2.0 prevents people using TF2 features from mixing garage into their own projects.

Dependency resolution is a really hard problem to solve and we can't do it in general, which is why I prefer to make garage as agnostic as possible about dependency versions. If not, we risk becoming like a Linux distribution, which curates a narrow slices of interoperating packages which work together. This is a lot to ask of the library (in practice, the Docker containers do this anyway).

**Comment by ryanjulian** [comment]
I pinned the version to >=1.4 to reflect our conversation. If you want to further constrain the TF or gast versions, I think you should do that in your own Pipfile.
