### ISSUE TITLE
metaworld.benchmarks can't be imported

### ISSUE THREAD

**Issue by sherlockbear** [rlworkgroup/garage#1816]
There is "No module named 'metaworld.benchmarks'". So I couldn't run examples/torch/mtsac_metaworld_ml1_pick_place.py correctly.

**Comment by avnishn** [comment]
Hi @sherlockbear thanks for trying out Metaworld and Garage. 

We (the Metaworld team) recently (in the last 2 weeks) upgraded Metaworld to a brand new API, however our Garage algorithms still use the old version of Metaworld that uses the old `metaworld.benchmarks` api.

You'll need to install the older Metaworld in your development environment for the time being, however we will update our examples by the end of the week.

To install the older Metaworld:

1)   uninstall your current version of metaworld (`pip uninstall metaworld`)
2)  update your environment using our `setup.py`, which when you run `pip install -e .[dev]` installs the correct version of Metaworld.

Hope this helps. I'm going to close this issue for now, but feel free to reopen and tag me if you have any more questions.

Best!
Avnish

**Comment by sherlockbear** [comment]
Thanks, looking forward to your update!

**Comment by sherlockbear** [comment]
So…Is there any update now?

**Comment by ryanjulian** [comment]
@sherlockbear @avnishn 's instructions tell you how to install a version of metaworld which is compatible with the current version of garage. If for some reason you want to install metaworld manually (rather than through garage's `setup.py`), you can use git hash `861ae8d8c4bef80a7ed86f47f47acaa494d4ab77` (see [here](https://github.com/rlworkgroup/garage/blob/master/setup.py#L61)).

We are working on updating to the new metaworld API in the branch `kr-new-metaworld-api`. There are no guarantees when it will be done, but it is likely it can be in within the next 2 weeks.

**Comment by sherlockbear** [comment]
Thanks very much, I have no more questions.
