### ISSUE TITLE
Docker Build COPY Error

### ISSUE THREAD

**Issue by eholly1** [rlworkgroup/garage#1898]
Checked out HEAD -> master @ 9861a9c3eb50de1d45ef58fea865f6cdf22a17be

`docker build -t garage-image docker/` from root dir, results in:
```
Step 29/61 : COPY --chown=$user:$user docker/entrypoint-runtime.sh $HOME/code/garage/docker/entrypoint-runtime.sh
COPY failed: stat /var/lib/docker/tmp/docker-builder547675387/docker/entrypoint-runtime.sh: no such file or directory
```

Fixed it locally by changing _Dockerfile:108_
`COPY --chown=$user:$user docker/entrypoint-runtime.sh $HOME/code/garage/docker/entrypoint-runtime.sh`

replace with
`COPY --chown=$user:$user entrypoint-runtime.sh $HOME/code/garage/docker/entrypoint-runtime.sh`

And similar change to _Dockerfile:131_

**Comment by eholly1** [comment]
With:
```
~/garage$ docker --version
Docker version 19.03.12, build 48a66213fe
```

**Comment by gitanshu** [comment]
Hi @eholly1 
Our docker setup assume the root garage directory to be the current context. For eg. in lines 164-168, we copy files from the root garage dir into the docker image. So we pass `.` instead of `docker/` as context and use `-f docker/Dockerfile` to point to the dockerfile. Also you probably want the target name `-t garage-dev-18.04` 

Also, we have a Makefile setup that we use for building docker images. There is some documentation for that here: https://garage.readthedocs.io/en/latest/user/docker.html#build-and-run-the-headless-image

If you prefer using docker build directly, here are the recipes we use:

https://github.com/rlworkgroup/garage/blob/9861a9c3eb50de1d45ef58fea865f6cdf22a17be/Makefile#L148-L157

https://github.com/rlworkgroup/garage/blob/9861a9c3eb50de1d45ef58fea865f6cdf22a17be/Makefile#L189-L199

Feel free to reopen the issue if you still have trouble or have some questions about this
