### ISSUE TITLE
release-2020.06 build broken by EnvSpec comparison

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#1940]
See https://travis-ci.com/github/rlworkgroup/garage/jobs/375464964#L1745

**Comment by ryanjulian** [comment]
@AiRuiChen do you have any idea about the root cause here?

**Comment by AiRuiChen** [comment]
> @AiRuiChen do you have any idea about the root cause here?

Not from looking at the error message. Before I changed EnvSpec comparison logic, it compares the addresses of EnvSpec objects and only returns True if they matches. Could be the case here?

**Comment by ryanjulian** [comment]
I think these EnvSpecs are from gym and not garage, but I could be wrong. Perhaps your fix needs to be backported if they are garage EnvSpec.

**Comment by AiRuiChen** [comment]
You are correct, the EnvSpecs are from gym. This test works fine before `Environment` related changes. If pinning gym version is the only difference, it could be a problem with the gym environment.

A quick fix might be `assert round_trip.spec == env.spec`, which compares the garage EnvSpec. Or simply remove the test. It is removed from master since [#1766 ](https://github.com/rlworkgroup/garage/commit/055b455ba18abcb8b7488a0b03da1fd8b8ab0216#diff-871176f53aa3d8337333571b8e2a8af5).
