### ISSUE TITLE
How slow is MTSAC on meta world 10?

### ISSUE THREAD

**Issue by TonyLianLong** [rlworkgroup/garage#2060]
My MTSAC training is really slow:
```
2020-09-15 10:52:34 | [mtsac_metaworld_mt10] epoch #19 | Saving snapshot...
2020-09-15 10:52:34 | [mtsac_metaworld_mt10] epoch #19 | Saved
2020-09-15 10:52:34 | [mtsac_metaworld_mt10] epoch #19 | Time 2494.48 s
2020-09-15 10:52:34 | [mtsac_metaworld_mt10] epoch #19 | EpochTime 124.84 s
```

I'm actually using commit 4c2470603a606bf055b2d661372b43b9f976643c and `examples/torch/mtsac_metaworld_mt10.py`. I wonder if there is actually regression of speed.

I using a 2080 Ti and I see only one core of CPU is being used. So we are actually not using multi-thread in generating samples?

What does epoch mean here? Is that the same as batch (for MT10, batch size is 150 * 10)? How many samples do each epoch have?
Is this normal that each epoch takes 124s? How long will it take to finish 20 Millions steps in the script?

**Comment by ryanjulian** [comment]
@avnishn

**Comment by avnishn** [comment]
Hi @TonyLianLong thanks for checking out Garage and Metaworld!

At the moment we only support single core sampling for that MTSAC.
In general, most RL algorithms are sampling bound, so the speed of a single epoch of training will be bound by the speed of a single core on the architecture that you're using. If a single core on your architecture is relatively slow, then it could lead to the runtime of a single epoch of training taking 124s. As a relative benchmark, I've run this example on MT10 and it takes me 10-20 hours to run depending on the architecture that I use

I'm in the process of using our `RaySampler` to update examples such as MTSAC, MTTRPO, and MTPPO to utilize multiple cores, but I don't plan to finish this change until the end of September.

My recommendation is to reduce the number of evaluation points that you need. Right now in that example, there are 500 eval points, but you can significantly reduce your runtime by turning this down to say 250. This is because at the end of these evaluation points, we collect a large number of evaluation samples, and you don't need many in order to track the progress of your learning agent or plot its results on a nice looking graph.

Did I answer your question? Feel free to @ me (@avnishn) if you have any more questions. I'd be more than happy to answer your questions!

**Comment by ryanjulian** [comment]
@avnishn isn't it also possible that this experiment is pickling the replay buffer? That can take a significant amount of time.

There's also no reason to think you can't use larger batches (i.e. parallel sampling), it just may make sample efficiency a little worse.

**Comment by avnishn** [comment]
@ryanjulian, I dont think it is because I disabled snapshotting in all of the examples in the repo. 

I'm going to close this for now, but please feel free to ask further questions either here or in our slack community.
