### ISSUE TITLE
Is pre-trained learning algorithm available ?

### ISSUE THREAD

**Issue by karthikarvind1295** [rlworkgroup/garage#2272]
Hello,

I am trying to use the MTSAC algorithm on metaworld ML10. Is there already available trained params.pkl file that I could use to test the environment (in Pytorch) ?

**Comment by avnishn** [comment]
Hi @karthikarvind1295,

Unfortunately, the garage team doesn't have the resources to make pretrained policies available for the metaworld benchmarks. 
I can tell you that in order to run MAML or RL2 for a meaningful amount of timesteps on ML10, it took about 2-3 days of runtime to run on an 8 core machine. I wouldn't recommend running it on a laptop for that long (I've blown up my laptop battery before, doing this).

You should check out the slack community for garage/metaworld (signup link inside the README). 
Also MTSAC is not meant to be used with metaworld ML10, but rather metaworld MT10. 

I'm going to close this issue for now, but feel free to reopen it if you have more questions with regards to this, and if you have more questions then please ask them on our slack community :) 

Thanks!
@avnishn
