### ISSUE TITLE
akro.Discrete() return randomly.

### ISSUE THREAD

**Issue by tianyma** [rlworkgroup/garage#2295]
Hi, I want to use discrete action space
`
self._action_space = akro.Discrete(4)
`
but I cannot get a discrete number in the `step` function, I got a list of 4 float type numbers, I am confused, can someone help me?

**Comment by krzentner** [comment]
In most of garage, we pass around "flattened" representations of observations and actions. For a discrete space, the flattened form is a one-hot encoding of the integer number. You should be able to convert it back to a number using `self._action_space.unflatten(action)` in this case.

I do recognize that this is confusing, and that it would probably be best if our core datatypes used unflattened data instead of flattened data.

**Comment by tianyma** [comment]
Thank you for your reply,  that works.
