### ISSUE TITLE
Don't import large dependencies transitively via convenience import

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#249]
i.e. I should not import {} unless I import something in {}
* (tensorflow, garage.tf)
* (theano, garage.theano)
* (pygame, garage.envs.box2d)
* (mujoco, garage.envs.mujoco)
* (dm_control, garage.envs.dm_control_env)

and so on...

**Comment by pelillian** [comment]
1. Get the dependency graph to determine where these all happen. (contacted Angel already)
2. Comment on each one and post in slack to ask peoples' opinions
3. Implement changes

**Comment by ryanjulian** [comment]
@jonashen can probably help walk you through this one

**Comment by ryanjulian** [comment]
I tried the static analysis approach today for a few minutes and found it pretty non-trivial.

I recommend you just do an quick audit of imports by reading the code and running some tests by hand.

For instance you can run a launcher which uses a gym environment and make sure pygame is not imported, run a box2D environment with an invalid MuJoCo key and make sure MuJoCo is not imported, run TF launchers and make sure Theano is not imported, etc.

That should be sufficient for the release, and then we can keep this issue open. I'm pretty sure pygame is getting imported pretty much always for some reason, but I can't recall a problem with the rest in the wild. Our logger currently has a TF dependency, so there's no way to avoid that one.

**Comment by gonzaiva** [comment]
Follow-up to this issue. Currently I'm running this [function](https://github.com/rlworkgroup/garage/blob/ecc04835de299be0e717f7edde100dc4da18ceae/scripts/travisci/check_modules_util.py) to check what things get imported for the following groups of modules in garage:
- [Base modules](https://github.com/rlworkgroup/garage/blob/ecc04835de299be0e717f7edde100dc4da18ceae/scripts/travisci/check_modules_base.py): all the modules that are not in the Theano or TF branch, or that are not part of garage.envs.*.
- [Envs modules](https://github.com/rlworkgroup/garage/blob/ecc04835de299be0e717f7edde100dc4da18ceae/scripts/travisci/check_modules_envs.py): all the modules that are in garage.envs, including mujoco, dm-control and box2d.
- [Tensorflow modules](https://github.com/rlworkgroup/garage/blob/ecc04835de299be0e717f7edde100dc4da18ceae/scripts/travisci/check_modules_tf.py): modules in garage.tf.
- [Theano modules](https://github.com/rlworkgroup/garage/blob/ecc04835de299be0e717f7edde100dc4da18ceae/scripts/travisci/check_modules_theano.py): modules in garage.theano.

There's only one error for the base, theano and envs modules, which is produced by importing tensorflow in garage.misc in order to use the logger, which is already commented by Ryan above. Other than that, no other non-required modules seem to be imported.

I was expecting to find pygame in base, theano and tf, but it's not getting imported in the corresponding scripts (except of course in envs). I did a manual check with grep, and this is what I found:
```
# pygame:    
  garage/envs/dm_control/dm_control_viewer.py:2:import pygame    
    DmControlViewer is only used by the DmControlEnv and the latter is not     
    imported in other garage packages    
    
  garage/misc/viewer2d.py:2:import pygame    
  garage/misc/viewer2d.py:3:import pygame.gfxdraw    
    The Viewer2D class isn't used in garage    
    
  garage/envs/box2d/mountain_car_env.py:2:import pygame    
  garage/envs/box2d/car_parking_env.py:2:import pygame    
  garage/envs/box2d/cartpole_swingup_env.py:2:import pygame    
    These don't get imported in any other garage package    
    
  garage/envs/box2d/box2d_viewer.py:4:import pygame    
  garage/envs/box2d/box2d_viewer.py:5:from pygame import KEYDOWN    
  garage/envs/box2d/box2d_viewer.py:6:from pygame import KEYUP    
  garage/envs/box2d/box2d_viewer.py:7:from pygame import MOUSEBUTTONDOWN       
  garage/envs/box2d/box2d_viewer.py:8:from pygame import MOUSEMOTION    
  garage/envs/box2d/box2d_viewer.py:9:from pygame import QUIT    
    Only the Box2DEnv imports the Box2DViewer class, and all the classes that  
    import Box2DEnv are garage.envs.box2d    
```
Those modules importing pygame outside garage/envs/box2d are not really used at all, so it seems pygame is not really imported if it's not required.

If you want me to re-run my check scripts with a different configuration, let me know: maybe I'm ignoring another module to check. Otherwise, I think we can clear this issue for the release.

**Comment by ryanjulian** [comment]
great. let's call it fixed and just keep a watchful eye.
