### ISSUE TITLE
Fix setup_xxx.sh scripts

### ISSUE THREAD

**Issue by jonashen** [rlworkgroup/garage#324]
### There are some major errors that need to be fixed in order for the scripts to work correctly.
- `Directory ‘.’ is not installable. File ‘setup.py’ not found.`
This script assumes that the individual will run the script in the `garage/` home directory. This should not be assumed.
 >**Potential solution**: recursively determine where the garage directory is located (relative or absolute path), then use that path to locate `setup.py` and replace `.` in the script.

- `SpecNotFound: Runtime error: Can't process without a name.`
This is a conda error, specifically on line 216 in `setup_osx.sh`: `conda env create -f environment.yml`. For some users, running this line with the relative path `environment.yml` will not work.
>**Potential solution**: recursively determine where the garage directory is located (relative or absolute path), then use that path to locate environment.yml and pass the full path in the script.
E.g. `conda env create -f /path/to/environment.yml`.

- Miniconda is not adding a name (i.e. "garage") to the created environment.
```$ conda env list 
# conda environments:
#
                  *  /miniconda/path/to/environment
^ missing garage here
```
>**Potential solution**: Not sure, don't have experience with miniconda. Maybe miniconda doesn't have naming functionality? Though I highly doubt it.

**Comment by ryanjulian** [comment]
* I think assuming we're in the garage repo top-level directory is a pretty mild assumption actually, which is really common in open source repos. We might want to barf and error if we detect we're *not* in the directory, but I think trying to find setup.py from an arbitrary PWD is a recipe for disaster. Replacing setup_xxx.sh with a Makefile would solve this problem but I don't think it's worth it.

* The conda bug is extremely strange. Are you saying it fails if i'm in `garage/` or if i'm elsewhere? because obviously it's going to fail if i'm not in `garage/` (which is where environment.yml is located).

**Comment by jonashen** [comment]
10.13.4

**Comment by ryanjulian** [comment]
@naeioi @pelillian @ahtsan since you guys just did new installs, can you verify whether or not this is still an issue and close and/or fix?

**Comment by pelillian** [comment]
@ryanjulian The conda bug didn't happen for me on OSX 10.13.6

**Comment by pelillian** [comment]
@ryanjulian @jonashen Would the simplest way to fix this be to just check the current working dir to see if it's the garage root directory? I can do that if needed.

**Comment by ryanjulian** [comment]
Just include a guard which checks we're in the correct directory. For instance, you can grep setup.py and make sure it has the line `name='rlgarage',`
