### ISSUE TITLE
Failed SIGINT integration test is not failing the build

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#339]
See: https://travis-ci.com/rlworkgroup/garage/jobs/150662098#L1687

Expected behavior: SIGINT integration test failure will trigger a build failure
Observed behavior: SIGINT integration test fails, but build succeeds

**Comment by gonzaiva** [comment]
That is the warning message produced at [run_experiment](https://github.com/rlworkgroup/garage/blob/f3b5ec1d97485a2f164698574c205bccebae17ec/scripts/run_experiment.py#L224-L238), and if the processes are still alive when this [assert](https://github.com/rlworkgroup/garage/blob/f3b5ec1d97485a2f164698574c205bccebae17ec/tests/integration_tests/test_sigint.py#L88) is executed.
It seems this a race condition where the processes do die, but right after run_experiment has also finished and before the assert gets executed, producing the warning message but not terminating the test.

**Comment by naeioi** [comment]
Failed case: https://travis-ci.com/rlworkgroup/garage/builds/87401046#L6251

**Comment by gonzaiva** [comment]
Okay, now that is the real deal, this bug never dies I guess, I'm back on it :(

**Comment by ryanjulian** [comment]
Rather than piling more and more time onto this bug, I think we should take a step back and think more critically about why this is happening, and if we can avoid it.

(0) What is the root cause of this behavior? Does it live in our code, a library, or Python?
(1) If it's not our code, are we misusing Python or a library?
(2) What about the design makes us vulnerable to this bug?
(3) Are there simple design changes which would completely avoid this bug?
(4) or do we need to make big changes to prevent this from happening?
(5) if 0-4 lead to the conclusion that it's really hard to avoid this bug, are our requirements simply unreasonable? Maybe we should then stop calling this a bug and start calling it misuse of the software?

**Comment by naeioi** [comment]
I try to clean up what actually happened at the very beginning of #120. 

**tl;dr** The original bug is caused by a python bug in `multiprocessing.Pool`, that parent process hangs and ignores `SIGINT` after children processes terminated.  

Quick clarification: the process(es) @ryanjulian  needed to kill manually after Ctrl+C are in sleep state, not zombie state, as had been mentioned by @gonzaiva . Indeed, zombie process cannot be killed by simply sending SIGINT. 

First, pressing Ctrl+C will send SIGINT to `run_experiment` process as well as all the worker processes started by `StatefulPool`. If I interpret correctly, there's no handler for SIGINT before patch #143 and #295, so the default behavior is to kill themselves.

Then, if worker process die before `run_experiment`, joblib might hang forever because of a python bug in `multiprocessing.Pool` (which joblib builds upon).
[Bug reproduction](https://stackoverflow.com/questions/1408356/keyboard-interrupts-with-pythons-multiprocessing-pool/2561809#2561809)
[Bug tracer](https://bugs.python.org/issue22393) (pending patch not merged until now)

------

So to answer your rumination on this problem:

(0) Before patch #295, it was a python bug. 

(1) an orchestrated shutdown, as implemented by #295, is [a suggested solution](https://stackoverflow.com/a/44869451) by the author of `multiprocessing` module. #295 is not working as expected probably because of some bugs in itself. 

(2) Because we use multiprocessing and we allow SIGINT to interrupt experiment. For me it looks inevitable.

(3) Following patches assume child process received SIGINT. (easy but no preferable)
-- (3a) [Someone](https://stackoverflow.com/a/1408476) claimed a timed blocked wait is free of this bug. 
-- (3b) rewrite StatefulPool to use `concurrent.futures` which is free of this bug. [Claim](https://bugs.python.org/issue9205#msg137913). 

(4) I believe fixing #295 (orchestrated shutdown) is the best option. It is also a good starting point we implement interrupt/resume mechanism of experiment.

(5) Interrupt a program and expect a full exit is a totally reasonable mindset. 
That being said, given experiment is oftentimes a long run task, we might borrow the idea how unix manages background long run service, and introduce a **garaged** mode that breaks garage into 'frontend' and 'backend', with frontend monitors and manages backend and backend runs tasks in the background. 
As an example, you might think about `mysqladmin` as an administration program to manage the `mysqld` daemon.

**Comment by gonzaiva** [comment]
Great observations @naeioi.
Moreover, I think we also have to consider one more process into this equation: the [manager process](https://github.com/rlworkgroup/garage/blob/f3b5ec1d97485a2f164698574c205bccebae17ec/garage/sampler/stateful_pool.py#L60).
This process holds a multiprocess reentrant lock used among the processes in the parallel sampler to [synchronize a counter](https://github.com/rlworkgroup/garage/blob/f3b5ec1d97485a2f164698574c205bccebae17ec/garage/sampler/stateful_pool.py#L222-L227) for the number of samples collected.
In #295, I added the [shutdown of this process](https://github.com/rlworkgroup/garage/blob/f3b5ec1d97485a2f164698574c205bccebae17ec/garage/sampler/stateful_pool.py#L70) into the orchestrated shutdown, however, I'm afraid that if one the process in the parallel sampler owns the manager's lock and then we kill the Manager, the other processes in the sampler waiting for the lock remain sleeping because the lock doesn't even exist anymore, which is pretty much what is happened in [Keren's build](https://travis-ci.com/rlworkgroup/garage/builds/87401046#L6251): a lot of sleeping processes instead of zombies.
I think this requires a some sort of redesign, because the manager's lock is heavily used through each iteration, and cover all possible scenarios under this may not lead us to the solution.
I think a solution would be to concentrate the counter in just one process, sent the samples of each process in the sampler to that process, and if the required number of samples has been reached, stop the processes the sampler.

**Comment by ryanjulian** [comment]
Perhaps the concurrency design is the real problem here. Having a counter is only necessary if you want to avoid ever collecting too many samples. We could also collect `>=` the number of samples desired and then truncate the collected set.

In that case, you can use a simple signal to coordinate. Processes collect samples until the signal tells them to exit.

**Comment by naeioi** [comment]
Running `test_sigint.py` on my own computer. 
There's a `orted` process that we have never seen before. 
Also a python is not killed and it's in running state. Not sleep, no zombie. 
```
Traceback (most recent call last):
  File "tests/fixtures/tf/trpo_cartpole_instrumented.py", line 48, in <module>
    plot=True,
  File "/media/kzhu/OS/Users/naeio/Documents/prog/18USC/resl/garage/garage/misc/instrument.py", line 524, in run_experiment
    command, shell=True, env=dict(os.environ, **env))
  File "/home/kzhu/miniconda2/envs/garage/lib/python3.6/subprocess.py", line 269, in call
    return p.wait(timeout=timeout)
  File "/home/kzhu/miniconda2/envs/garage/lib/python3.6/subprocess.py", line 1457, in wait
    (pid, sts) = self._try_wait(0)
  File "/home/kzhu/miniconda2/envs/garage/lib/python3.6/subprocess.py", line 1404, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
The following processes didn't die after the shutdown of run_experiment:
{'ppid': 7225, 'cmdline': ['orted', '--hnp', '--set-sid', '--report-uri', '10', '--singleton-died-pipe', '11', '-mca', 'state_novm_select', '1'], 'status': 'sleeping', 'pid': 7270, 'name': 'orted'}
This is a sign of an unclean shutdown. Please reopen the following issue
with a detailed description of how the error was produced:
https://github.com/rlworkgroup/garage/issues/120
Traceback (most recent call last):
  File "/media/kzhu/OS/Users/naeio/Documents/prog/18USC/resl/garage/scripts/run_experiment.py", line 242, in <module>
    run_experiment(sys.argv)
  File "/media/kzhu/OS/Users/naeio/Documents/prog/18USC/resl/garage/scripts/run_experiment.py", line 185, in run_experiment
    method_call(variant_data)
  File "tests/fixtures/tf/trpo_cartpole_instrumented.py", line 36, in run_task
    algo.train()
  File "/media/kzhu/OS/Users/naeio/Documents/prog/18USC/resl/garage/tests/fixtures/tf/instrumented_batch_polopt.py", line 46, in train
    samples_data = self.process_samples(itr, paths)
  File "/media/kzhu/OS/Users/naeio/Documents/prog/18USC/resl/garage/garage/tf/algos/batch_polopt.py", line 107, in process_samples
    return self.sampler.process_samples(itr, paths)
  File "/media/kzhu/OS/Users/naeio/Documents/prog/18USC/resl/garage/garage/tf/samplers/batch_sampler.py", line 58, in process_samples
    self.algo.baseline.predict(path) for path in paths
  File "/media/kzhu/OS/Users/naeio/Documents/prog/18USC/resl/garage/garage/tf/samplers/batch_sampler.py", line 58, in <listcomp>
    self.algo.baseline.predict(path) for path in paths
  File "/media/kzhu/OS/Users/naeio/Documents/prog/18USC/resl/garage/garage/tf/baselines/gaussian_mlp_baseline.py", line 52, in predict
    return self._regressor.predict(path["observations"]).flatten()
  File "/media/kzhu/OS/Users/naeio/Documents/prog/18USC/resl/garage/garage/tf/regressors/gaussian_mlp_regressor.py", line 286, in predict
    return self._f_predict(xs)
  File "/media/kzhu/OS/Users/naeio/Documents/prog/18USC/resl/garage/garage/tf/misc/tensor_utils.py", line 11, in run
    return sess.run(outputs, feed_dict=dict(list(zip(inputs, input_vals))))
  File "/home/kzhu/miniconda2/envs/garage/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/kzhu/miniconda2/envs/garage/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/kzhu/miniconda2/envs/garage/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/kzhu/miniconda2/envs/garage/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/kzhu/miniconda2/envs/garage/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/kzhu/miniconda2/envs/garage/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
KeyboardInterrupt
.
======================================================================
FAIL: test_sigint:11
'tests/fixtures/tf/trpo_cartpole_instrumented.py', <ExpLifecycle.UPDATE_PLOT: 5 (tests.integration_tests.test_sigint.TestSigInt)
Interrupt the experiment in different stages of its lifecyle.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/kzhu/OS/Users/naeio/Documents/prog/18USC/resl/garage/tests/integration_tests/test_sigint.py", line 98, in test_sigint
    interrupt_experiment(experiment_script, exp_stage)
  File "/media/kzhu/OS/Users/naeio/Documents/prog/18USC/resl/garage/tests/integration_tests/test_sigint.py", line 88, in interrupt_experiment
    assert clean_exit, colorize(error_msg, "red")
AssertionError: These processes didn't die during ExpLifecycle.UPDATE_PLOT:
{'name': 'python', 'cmdline': ['python', '/media/kzhu/OS/Users/naeio/Documents/prog/18USC/resl/garage/scripts/run_experiment.py', '--n_parallel', '6', '--snapshot_mode', 'last', '--seed', '1', '--plot', 'True', '--exp_name', 'experiment_2018_10_11_15_18_23_0001', '--log_dir', '/media/kzhu/OS/Users/naeio/Documents/prog/18USC/resl/garage/data/local/experiment/experiment_2018_10_11_15_18_23_0001', '--use_cloudpickle', 'True', '--args_data', 'gASVuQQAAAAAAACMF2Nsb3VkcGlja2xlLmNsb3VkcGlja2xllIwOX2ZpbGxfZnVuY3Rpb26Uk5QoaACMCXN1YmltcG9ydJSTlIwNdGVuc29yZmxvdy5ubpSFlFKUMGgEjBB0ZW5zb3JmbG93LnRyYWlulIWUUpQwaACMD19tYWtlX3NrZWxfZnVuY5STlGgAjA1fYnVpbHRpbl90eXBllJOUjAhDb2RlVHlwZZSFlFKUKEsASwBLBUsMS0dDYHQAdAF0AoMAgwGDAX0BdAN8AWoEZA10BWoGagdkAGQCjQR9AnQIfAFqBHQJZA5kA40BZASNAn0DdAp8AXwCfANkBWQGZAdkCGQJZApkC2QMjQp9BHwEaguDAAEAZABTAJQoTksgKIwIZW52X3NwZWOUjAxoaWRkZW5fc2l6ZXOUjBNoaWRkZW5fbm9ubGluZWFyaXR5lIwTb3V0cHV0X25vbmxpbmVhcml0eZR0lGgUhZRoE4wOcmVncmVzc29yX2FyZ3OUhpRNAARLZEsERz/vrhR64UeuRz/vXCj1wo9cRwAAAAAAAAAAiCiMA2VudpSMBnBvbGljeZSMCGJhc2VsaW5llIwKYmF0Y2hfc2l6ZZSMD21heF9wYXRoX2xlbmd0aJSMBW5faXRylIwIZGlzY291bnSUjApnYWVfbGFtYmRhlIwQcG9saWN5X2VudF9jb2VmZpSMBHBsb3SUdJRLIEsghpRLIEsghpR0lCiMBVRmRW52lIwJbm9ybWFsaXpllIwLQ2FydHBvbGVFbnaUjBFHYXVzc2lhbk1MUFBvbGljeZSMBHNwZWOUjAJ0ZpSMAm5ulIwEdGFuaJSME0dhdXNzaWFuTUxQQmFzZWxpbmWUjARkaWN0lIwQSW5zdHJ1bWVudGVkVFJQT5SMBXRyYWlulHSUKIwBX5RoG2gcaB2MBGFsZ2+UdJSML3Rlc3RzL2ZpeHR1cmVzL3RmL3RycG9fY2FydHBvbGVfaW5zdHJ1bWVudGVkLnB5lIwIcnVuX3Rhc2uUSwxDKgABDgECAQQBAgEGAQgCAgEEAQ4CAgECAQIBAgECAQIBAgECAQIBAgEIApQpKXSUUpRK/////4wIX19tYWluX1+Uh5RSlH2UKIwHZ2xvYmFsc5R9lChoKYwTZ2FyYWdlLnRmLmVudnMuYmFzZZRoKZOUaDGMKWdhcmFnZS50Zi5iYXNlbGluZXMuZ2F1c3NpYW5fbWxwX2Jhc2VsaW5llGgxk5RoM4wjdGVzdHMuZml4dHVyZXMudGYuaW5zdHJ1bWVudGVkX3RycG+UaDOTlGgqjBpnYXJhZ2UuZW52cy5ub3JtYWxpemVkX2VudpSMDU5vcm1hbGl6ZWRFbnaUk5RoK4weZ2FyYWdlLmVudnMuYm94MmQuY2FydHBvbGVfZW52lGgrk5RoLIwmZ2FyYWdlLnRmLnBvbGljaWVzLmdhdXNzaWFuX21scF9wb2xpY3mUaCyTlGguaASMCnRlbnNvcmZsb3eUhZRSlHWMCGRlZmF1bHRzlE5oMn2UjA5jbG9zdXJlX3ZhbHVlc5ROjAZtb2R1bGWUaD6MBG5hbWWUaDqMA2RvY5ROjAhxdWFsbmFtZZRoOnV0Ui4=', '--variant_data', 'gAN9cQBYCAAAAGV4cF9uYW1lcQFYIwAAAGV4cGVyaW1lbnRfMjAxOF8xMF8xMV8xNV8xOF8yM18wMDAxcQJzLg=='], 'pid': 4457, 'status': 'running'}
{'name': 'orted', 'cmdline': ['orted', '--hnp', '--set-sid', '--report-uri', '10', '--singleton-died-pipe', '11', '-mca', 'state_novm_select', '1'], 'pid': 4504, 'status': 'sleeping'}


======================================================================
FAIL: test_sigint:12
'tests/fixtures/tf/trpo_cartpole_instrumented.py', <ExpLifecycle.SHUTDOWN: 6> (tests.integration_tests.test_sigint.TestSigInt)
Interrupt the experiment in different stages of its lifecyle.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/kzhu/OS/Users/naeio/Documents/prog/18USC/resl/garage/tests/integration_tests/test_sigint.py", line 98, in test_sigint
    interrupt_experiment(experiment_script, exp_stage)
  File "/media/kzhu/OS/Users/naeio/Documents/prog/18USC/resl/garage/tests/integration_tests/test_sigint.py", line 88, in interrupt_experiment
    assert clean_exit, colorize(error_msg, "red")
AssertionError: These processes didn't die during ExpLifecycle.SHUTDOWN:
{'name': 'python', 'cmdline': ['python', '/media/kzhu/OS/Users/naeio/Documents/prog/18USC/resl/garage/scripts/run_experiment.py', '--n_parallel', '6', '--snapshot_mode', 'last', '--seed', '1', '--plot', 'True', '--exp_name', 'experiment_2018_10_11_15_18_47_0001', '--log_dir', '/media/kzhu/OS/Users/naeio/Documents/prog/18USC/resl/garage/data/local/experiment/experiment_2018_10_11_15_18_47_0001', '--use_cloudpickle', 'True', '--args_data', 'gASVuQQAAAAAAACMF2Nsb3VkcGlja2xlLmNsb3VkcGlja2xllIwOX2ZpbGxfZnVuY3Rpb26Uk5QoaACMCXN1YmltcG9ydJSTlIwNdGVuc29yZmxvdy5ubpSFlFKUMGgEjBB0ZW5zb3JmbG93LnRyYWlulIWUUpQwaACMD19tYWtlX3NrZWxfZnVuY5STlGgAjA1fYnVpbHRpbl90eXBllJOUjAhDb2RlVHlwZZSFlFKUKEsASwBLBUsMS0dDYHQAdAF0AoMAgwGDAX0BdAN8AWoEZA10BWoGagdkAGQCjQR9AnQIfAFqBHQJZA5kA40BZASNAn0DdAp8AXwCfANkBWQGZAdkCGQJZApkC2QMjQp9BHwEaguDAAEAZABTAJQoTksgKIwIZW52X3NwZWOUjAxoaWRkZW5fc2l6ZXOUjBNoaWRkZW5fbm9ubGluZWFyaXR5lIwTb3V0cHV0X25vbmxpbmVhcml0eZR0lGgUhZRoE4wOcmVncmVzc29yX2FyZ3OUhpRNAARLZEsERz/vrhR64UeuRz/vXCj1wo9cRwAAAAAAAAAAiCiMA2VudpSMBnBvbGljeZSMCGJhc2VsaW5llIwKYmF0Y2hfc2l6ZZSMD21heF9wYXRoX2xlbmd0aJSMBW5faXRylIwIZGlzY291bnSUjApnYWVfbGFtYmRhlIwQcG9saWN5X2VudF9jb2VmZpSMBHBsb3SUdJRLIEsghpRLIEsghpR0lCiMBVRmRW52lIwJbm9ybWFsaXpllIwLQ2FydHBvbGVFbnaUjBFHYXVzc2lhbk1MUFBvbGljeZSMBHNwZWOUjAJ0ZpSMAm5ulIwEdGFuaJSME0dhdXNzaWFuTUxQQmFzZWxpbmWUjARkaWN0lIwQSW5zdHJ1bWVudGVkVFJQT5SMBXRyYWlulHSUKIwBX5RoG2gcaB2MBGFsZ2+UdJSML3Rlc3RzL2ZpeHR1cmVzL3RmL3RycG9fY2FydHBvbGVfaW5zdHJ1bWVudGVkLnB5lIwIcnVuX3Rhc2uUSwxDKgABDgECAQQBAgEGAQgCAgEEAQ4CAgECAQIBAgECAQIBAgECAQIBAgEIApQpKXSUUpRK/////4wIX19tYWluX1+Uh5RSlH2UKIwHZ2xvYmFsc5R9lChoLmgEjAp0ZW5zb3JmbG93lIWUUpRoK4weZ2FyYWdlLmVudnMuYm94MmQuY2FydHBvbGVfZW52lGgrk5RoKYwTZ2FyYWdlLnRmLmVudnMuYmFzZZRoKZOUaDGMKWdhcmFnZS50Zi5iYXNlbGluZXMuZ2F1c3NpYW5fbWxwX2Jhc2VsaW5llGgxk5RoKowaZ2FyYWdlLmVudnMubm9ybWFsaXplZF9lbnaUjA1Ob3JtYWxpemVkRW52lJOUaDOMI3Rlc3RzLmZpeHR1cmVzLnRmLmluc3RydW1lbnRlZF90cnBvlGgzk5RoLIwmZ2FyYWdlLnRmLnBvbGljaWVzLmdhdXNzaWFuX21scF9wb2xpY3mUaCyTlHWMCGRlZmF1bHRzlE5oMn2UjA5jbG9zdXJlX3ZhbHVlc5ROjAZtb2R1bGWUaD6MBG5hbWWUaDqMA2RvY5ROjAhxdWFsbmFtZZRoOnV0Ui4=', '--variant_data', 'gAN9cQBYCAAAAGV4cF9uYW1lcQFYIwAAAGV4cGVyaW1lbnRfMjAxOF8xMF8xMV8xNV8xOF80N18wMDAxcQJzLg=='], 'pid': 4651, 'status': 'running'}
{'name': 'orted', 'cmdline': ['orted', '--hnp', '--set-sid', '--report-uri', '10', '--singleton-died-pipe', '11', '-mca', 'state_novm_select', '1'], 'pid': 4696, 'status': 'sleeping'}
```

**Comment by gonzaiva** [comment]
The `orted` process is new to me as far as multiprocessing errors I have seen. I used the package configuration for box2d-py and gym in #335, which is what @naeioi used to detonate the issue above with the orted process, but I haven't had the "luck" in finding this conflicting process in my tests.
Also, I have been running test_sigint in a loop to catch the error detected in [Keren's build](https://travis-ci.com/rlworkgroup/garage/builds/87401046#L6251) and spot where the sleeping processes are staying, but after 18 iterations I haven't had any luck. I will keep trying, but this sort of problems seem to be more prone to occur in TravisCI.
I'm using Docker with limited memory and CPUs to have a similar configuration as in Travis though.
I will keep trying this and read about joblib and loky to spot any hints towards why we're facing these issues.

**Comment by ryanjulian** [comment]
Are you both using Linux, or is someone using Mac? multiprocessing backends can differ between platforms.

**Comment by gonzaiva** [comment]
Both Linux, although Keren is using Ubuntu 18 and I'm using Ubuntu 16.

**Comment by gonzaiva** [comment]
I was curious in trying Python 3.7, but it seems there's [no pip package](https://github.com/tensorflow/tensorflow/issues/20444) for TensorFlow in that version of Python yet.

**Comment by naeioi** [comment]
@gonzaiva @ryanjulian Should we simply turn off SIGINT test in CI for now because it is not ready yet? It still blocks PR from time to time. https://travis-ci.com/rlworkgroup/garage/builds/89072950

**Comment by ryanjulian** [comment]
Let's let is sit for now unless it starts being a big impediment. I think it's a healthy reminder that we need to fix this.
