### ISSUE TITLE
Docker cache is vulnerable to silently-upgraded dependencies

### ISSUE THREAD

**Issue by naeioi** [rlworkgroup/garage#346]
Currently in CI docker fetches image of latest successful build as cache. This will skip installation of all the dependencies, including apt and python modules, if dependencies description remains unchanged (e.g. `environment.yml`). 

This is problematic however, that the change in dependency repository can possibly render it incompatible with our code. The latest example is update of `dm_control` #344. Even in presence of such corrupt dependency CI might still falsely pass because all deps are cached. 

So given purpose of cron CI I suggest turning off cache using `docker build --no-cache`. (For an ordinary CI it's fine to enable cache to speedup building)

**Comment by ryanjulian** [comment]
Can you explain more? The Docker cache only includes commits which were sent to master, and the cron job also runs on master. That means that the cron job should never have to rebuild the docker.

**Comment by ryanjulian** [comment]
Can you provide a Travis link reproducing the issue?

**Comment by naeioi** [comment]
[cron CI is failing](https://travis-ci.com/rlworkgroup/garage/builds/88499121).

From the Travis log, [a recent update](https://hub.docker.com/r/library/ubuntu/tags/) in docker's library/ubuntu invalidates all the cache and as a result all the deps are retrieved and installed from source repository. I suspect some deps that are not locked but get upgraded since last successful build are to be blamed for this failure.

**Comment by ryanjulian** [comment]
It's not just the cron job, it's all CI builds. There is more than one issue here.

Can you explain how *our* cache is invalidated by library/ubuntu? That seems impossible.

**Comment by naeioi** [comment]
@ryanjulian Because in docker, layers are stacked and each one is a delta of the changes from the previous layer. If one layer for some reason get invalidated, all the following layers are invalidated. This is why [docker suggests](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#use-multi-stage-builds)
> order them (layers) from the less frequently changed (to ensure the build cache is reusable) to the more frequently changed

In our case setting up library/ubuntu is [the first layer](https://travis-ci.com/rlworkgroup/garage/builds/88499121#L594) of our docker image. So all the following cache layers are invalidated. This affects all CI builds, because both PR builds or cron builds has library/ubuntu as the first layer.

**Comment by ryanjulian** [comment]
Are you are saying that `ubuntu:16.04` got updated, invalidating our whole cache?

That sounds fine to me. That would mean that the cache would be updated either by the cron build or the next time someone submits an new PR to `master`. Did that not happen?

**Comment by ryanjulian** [comment]
> In our current setting, only next successful cron build will update cache. See
`master` gets a branch build every time a new PR is submitted, and also for every cron. A PR build is run before submit, and a branch build (on master) is run after submit.

**Comment by ryanjulian** [comment]
@naeioi given my explanation, what do you think the next action is for this issue?

**Comment by ryanjulian** [comment]
Given their interest in packaging, I think @CatherineSue and @utkarshjp7 should read this thread. I'm also interested in @krzentner 's and @dmillard 's perspectives, since I always enjoy it when people tell me I'm wrong.

1. Yes. If your software doesn't install the first time, most people won't use it.
1. There are a couple more options
a) __lock all dependencies__
yes. this is an option. it would make a little (not a lot) more work for us than the current system when we upgrade a dependency.
b) __change pkg/environment mgmt tool__
          i'm in favor of this for unrelated reasons, but it won't change a big part of the problem, which is installation time and detecting changes to deps.
i. installation time -- regardless of how you track deps, the only way to verify the system is working is to install them all and run tests on a clean image every time there is a change. our system has unavoidable system-level dependencies (e.g. OpenGL), so this is always going to take a long time in a monolithic repo.
ii. detecting changes -- i believe this is the actual root of the issue, and discuss in more detail below
c) __have fewer dependencies__
i'm surprised no one has mentioned this one. if you have too many dependencies to install during test time, the most obvious thing to do is to have fewer of them. every dependency is a point of failure, and major deps are major points of failure. what's more, you have to ensure that the cross-product of all your dependencies work together. it's likely that garage's dependency list is significantly longer than it really needs to be, and that actually makes the software harder to write and maintain.
d) __split up the software so individual units have fewer dependencies__
this is really just a different version of (c), but it can help a lot. if you have a single distribution unit with 100 dependencies, you have to install all 100 dependencies and then test all (e.g. a lot) of the software against those. if you have 10 distribution units each with 10 dependencies, then you can do the bulk of the testing in jobs with <10 dependencies and 1/10 the code. you still, at some point, need to install all 100 deps and all 10 distribution units, and run a series of integration tests, but the integrity implied by the lower-level of testing means these can be fewer and less frequent. this is the unit testing vs integration testing split. you might just need more units.
e) __do nothing__ (i.e. 3 above)
i believe your comment about `ubuntu:16.04` updates corrupting cache coherency is not accurate. the cron build on master executes every night, and if `ubuntu:16.04` is updated, docker will detect this and build our image from scratch with the new upstream. at the conclusion of the build it will upload the new cache (based on the new `ubuntu:16.04`) to the docker hub, where it will be the cache for all subsequent builds. furthermore, every build detects whether the entire entire cache has been invalidated. in your `ubuntu:16.04` update-with-no-cache-update scenario, every build off of master would rebuild the entire image--making the builds take a long time, and possibly fail to finish--but it would not silently pass corrupt dependencies.

**root cause (IMHO): change detection**
The original impetus of this bug was an update to `dm_control` leading to silent installation failure. This happened because our Docker cache became stale without getting automatically updated. The root cause is in the change detection algorithm, and tells us what we could change to make it not happen again.

Docker's change detection algorithm is file-based. If the files which are used as input to a layer (e.g. `RUN`) change (in the MD5 sense), then the layer is rebuilt. To turn this into dependency-based change detection, we use the dependency file (environment.yml) as input to one of our Docker layers. the dependency file lists version/git hashes for all major deps, and leaves the rest unconstrained so that conda doesn't fail to solve the dependency graph. The assumption is that **a breaking change in a dependency will always correspond to a textual change in the dependency file (e.g. a version bump).** This is a pretty valid assumption for well-maintained open source software which uses a semantic versioning scheme. It fails when software gets updated frequently with breaking changes and/or doesn't have meaningful semantic versioning.

Our policy so far has been to pin obviously-major dependencies (e.g. numpy, tensorflow, theano), and only pin versions for the rest as-needed (e.g. when they prove themselves unworthy of trust by breaking something). In that sense, our system has worked because we now know to pin `dm_control`. It would have been nice to have automatically detected the failure in the CI, but your major contribution is to point out that our caching scheme prevented that. With no Docker cache we would have certainly detected the `dm_control` breakage, probably within hours of the offending commit.

The only way for us to detect these dependency failures in the CI is to either (a) turn off caching or (b) ensure that the change detection invariant remains true. I think (a) is a poor option because it makes developer's lives harder and thus makes us less-likely to fully test the software. For instance, even with infinite parallel Travis jobs, a full Docker build would make every test suite take a minimum of 40 minutes.

So let's explore (b): enforcing the change detection invariant. One way of doing this is to pin all versions, and it's probably the only thing that we can do immediately. The trouble with pinning all versions is that is obscures which versions *matter* and which versions *don't matter*.

Some versions will be pinned because they really do matter (e.g. TF), and others will be pinned so that we can detect arbitrary changes. It's likely that the versions for a set of 20 dependencies will become mutually-incompatible if you update one of them. If you pin all your versions, the dependency resolution tool can't help you find a new stable set. What's more, you probably can't even help yourself by unpinning versions, because you have no information about which version numbers you're allowed to relax in order to unstick the dependency tool (e.g. pip, conda). That is to say, pinning all versions destroys important information.

Dependency versioning systems deal with this by maintaining two files: the canonical dependency list with only some version pins, and a file containing the most recent solution to that file (sometimes called the locked dependency file). Every time a new solution to the dependency list is found, the lockfile is updated, but the canonical list remains the same. Given these two, your CI can detect changes in the *solution* even if none of the *constraints* changed. This would correspond to us using a lockfile as input to Docker, rather than just environment.yml.

This can be implemented with any dependency manager (e.g. you just need to get it to produce a list of current packages and versions), but they vary in their level of automation. To my knowledge, to build lockfiles with conda or pip you would have to explicitly dump the output of `pip freeze` or `conda list` into a text file before every commit (this could be achieved with a pre-commit hook, for instance). pipenv does this automatically (into Pipfile.lock) every time it solves the environment.

**tl;dr: we should probably focus on switching to pipenv and splitting up the repo, both of which will improve this problem with little additional work from us**

**Comment by naeioi** [comment]
@ryanjulian I think you have made an (almost) thorough observation of this issue. One point you mentioned and IMO very important but I totally missed is that we should never pin all versions, otherwise we get into trouble when later we want to upgrade dependencies.

As for pip and conda we are using now, I suspect that `pip freeze` or `conda list` only dumps pinned version of packages currently locally installed, so this will not help to detect dependency changes. The correct way I believe is to instruct the dependency manager to resolve dependencies **_only_** from `environment.yml` (or some other dep description file) and regardless of anything else. I did some research and found `pip-compile` to be such tool for pip but I didn't find one for conda. So switching to pipenv might be the ultimate solution. Once we have lockfile, we can instruct CI to rebuild from scratch only when dependency changes. 

I haven't looked too much into `pipenv`. I think I need more research for a better understanding of the best practice of python package management (I even haven't read your post on slack, but will do).
