### ISSUE TITLE
Replace Enum parameters with strings

### ISSUE THREAD

**Issue by amolchanov86** [rlworkgroup/garage#435]
Hi everyone, 
I would like to share the problem that I encountered that explains why I typically prefer using strings for parameters that are choice-based instead of enums.

I had to copy and re-define all classes of the hierarchy ppo > npo > batch_polopt, but I forgot to import my definition of PGLoss in ppo.py (i.e. I accidentally kept line import garage.tf.algos.npo import PGLoss instead of using the reference to my newly created module) to feed PGLoss.CLIP to the NPO initializer. As a result, PGLoss(Enum) class was used from the original garage module, but then re-defined in my module with the same name. As a result line like PGLoss.CLIP == PGLoss.CLIP would evaluate in False during if statements inside of NPO since those were different PGLoss classes.
That is why I prefer using strings and just give a description of options you have with a string in parameter description. This way, say "LOSS_CLIP" == "LOSS_CLIP" would, obviously, give True, as it should.
On top of that using strings allows storing all parameters in yaml file and feed them directly to corresponding functions/classes after reading yaml to a dictionary. 
Hence, I believe this might a feature request to consider.

PS: Btw, thanks guys that you actually have asserts when if-else runs out of options (the rule of thumb - check and assert inputs whenever possible). It is a good style! Having default silent options often leads to bugs that are very hard to notice.

**Comment by ryanjulian** [comment]
@krzentner what are your thoughts?

@amolchanov86 can you show the code snippet which broke? I've been on the fence about enums vs strings for a while, too.

**Comment by ryanjulian** [comment]
Did your NPO fall through to https://github.com/rlworkgroup/garage/blob/master/garage/tf/algos/npo.py#L329? That is our hope.

Note that we made the Enum string-valued so that you can pass the string instead and it will still work.

I wonder if it would have been better if the Enum were strings instead? I guess you would not have gotten any error, but is that what we want? This only seems to be a problem if you're going to copy NPO, rather than subclass it or use it.

Alas, I wish Python had a proper `switch`--then static analysis could force you to handle all possible switch cases in an Enum. Right now we can only force it in code review.

**Comment by krzentner** [comment]
This report is surprising to me, because I thought that string-valued enums with the same value would compare equal to each other. I guess I shouldn't be surprised that they don't. It also seems like static analysis should catch this, but I don't think that's actually a strong argument, since I don't believe anyone actually uses static analysis in garage (or most of Python). We certainly can't expect our users to be using e.g. mypy.

Thinking about this a bit more, reading this report actually convinced me that enums are not a great fit for our use cases. We largely use enums to select between different variants of some portion of an algorithm. Enums are valuable for this use case when the same set of variants are available across all algorithms. In those cases, we should refactor out the enum to a common module, not copy and paste it. **However**, I think many of our use cases actually involve different algorithms taking slightly different enums. Since [Python doesn't allow extending enums](https://docs.python.org/3/library/enum.html#restricted-enum-subclassing), this forces copy and pasting the whole enum every time we want to change it slightly.

Worse, this is going to be really hard for our users to debug. They might switch between two similar algorithms, but pass the enum from one into the other. If they're using a type checker, they might notice this is wrong, but otherwise are likely to get an incredibly mysterious assertion (or, if we mess up, silently wrong behaviour).

For this reason, I now agree with Artem that we're better off not using enums. In the worst case, we will merely be more consistent with most other python APIs.

**Comment by ryanjulian** [comment]
Alright I'll turn this into "replace the enums with strings" and mark it as an FR.

**Comment by CatherineSue** [comment]
I agree with the above discussion.

**Comment by ryanjulian** [comment]
Alright great. This one is relatively low-priority--whenever someone gets the chance.

**Comment by CatherineSue** [comment]
Fixed in #632.
