### ISSUE TITLE
sim_policy not working

### ISSUE THREAD

**Issue by xht033** [rlworkgroup/garage#690]
Hi, 
I just found that sim_policy.py cannot work. 
data that read from "params.pkl" does not include the key of "policy"

**Comment by ryanjulian** [comment]
@zequnyu @naeioi can you take a look?

**Comment by naeioi** [comment]
@xht033 True. Thanks for reporting! This is because starting from https://github.com/rlworkgroup/garage/commit/3cd1718eece4f3c1cbae6f63cc409ee1e79720c1 we save `algo`  instead of `policy`. If you are eager for a quick fix, try replacing `data['policy']` by `data['algo'].policy`. Or wait for my PR expected to file tommorow.

**Comment by xht033** [comment]
Thanks!
