### ISSUE TITLE
Parallel sampling for TRPO and PPO with GaussianMLPPolicyWithModel

### ISSUE THREAD

**Issue by ilinojkovic** [rlworkgroup/garage#767]
I'm looking into the `n_parallel` variable in `experiment_wrapper.run_experiment`, and I'm a bit confused. Per documentation, this should be the number of parallel workers to perform rollouts, but it seems that even when `n_parallel > 1` the sampling is still done in one process.

I'm running TRPO and PPO with `GaussianMLPPolicyWithModel` using `LocalRunner`, and looking at the code, it seems that in both cases the sampler used is `OnPolicyVectorizedSampler` which doesn't utilize `parallel_sampler` as in `BatchSampler`. When we have one environment, this makes sense, since each action in the rollout is dependent on previous ones, however, when there is a vector of multiple environments isn't this parallelizable?

Is there a way to run parallel sampling when there's `n_env > 1` in this scenario?

**Comment by ryanjulian** [comment]
I apologize that the sampling code is hard to understand right now. We are in the midst of rewriting a lot of it.

`OnPolicyVectorizedSampler` uses a `VecEnvExecutor` rather than the parallel sampling multiprocessing pool. That is, it constructs `n` environments in the current process and samples them all at once, one observation at a time . We use this as the default (we call it vectorized sampling) because it's actually faster in practice than launching multiple processes (which we call batch sampling).

There are some algorithms which might require batch sampling. For those, we have the `BatchSampler`. You can see an example for how to use it [here](https://github.com/rlworkgroup/garage/blob/master/examples/tf/trpo_cartpole_batch_sampler.py)

**Comment by avnishn** [comment]
> I apologize that the sampling code is hard to understand right now. We are in the midst of rewriting a lot of it.
> 
> `OnPolicyVectorizedSampler` uses a `VecEnvExecutor` rather than the parallel sampling multiprocessing pool. That is, it constructs `n` environments in the current process and samples them all at once, one observation at a time . We use this as the default (we call it vectorized sampling) because it's actually faster in practice than launching multiple processes (which we call batch sampling).
> 
> There are some algorithms which might require batch sampling. For those, we have the `BatchSampler`. You can see an example for how to use it [here](https://github.com/rlworkgroup/garage/blob/master/examples/tf/trpo_cartpole_batch_sampler.py)

look particularly at the n_envs parameter.

**Comment by ilinojkovic** [comment]
Thank you both for the answers. I just tested the `BatchSampler` as per example, and as @ryanjulian says, it's indeed slower then vectorized sampling. This seems odd to me, if we have a fixed policy, shouldn't we be able to perform all rollouts independently? Currently I experience a linear increase in sampling time along number of environments, which for lengthy rollouts can be significant.

**Comment by ryanjulian** [comment]
There is a large overhead in transmitting the policy parameters between OS processes, then transmitting the rollouts collected in those processes back to the main training process.

**Comment by ilinojkovic** [comment]
I see. Thanks for clarification.
