### ISSUE TITLE
Action space bounds not regarded for GaussianMLPPolicy and GaussianMLPPolicyWithModel

### ISSUE THREAD

**Issue by ilinojkovic** [rlworkgroup/garage#769]
It seems that action space bounds provided by the environment aren't taken into account in `GaussianMLPPolicy` and `GaussianMLPPolicyWithModel`. Shouldn't the actions be sampled only from the defined Box?

**Comment by ryanjulian** [comment]
This is a common misconception. The short answer is no, they should not be clipped by the model to the action space bounds.

The output of a Gaussian distribution is unbounded. Clipping the outputs (in the differentiable path) would be a different model class, because it would imply bounded output domain, which a Gaussian is incapable of modeling. If the agent is truly represented by a Gaussian distribution, them the agent's outputs cannot be bounded.

This matters a lot for the analysis of the algorithm. Furthermore, the gradient behavior around the clipping region can be very problematic (e.g. very high variance and unstable) for numerical optimizers, especially SGD.

It is the environment's job to enforce its interface, including the action space. If the environment clips action inputs to the action space bounds, the agent will generally learn that exceeding these bounds has no effect, and learn to bound its actions. This has the intended effect (bounding the agent's output in practice), while avoiding the numerical nastiness of hard clip regions.

If you feel strongly about this design decision in RL algorithms, I suggest you take a look into [research into beta distribution policies](https://scholar.google.com/scholar?rlz=1C5CHFA_enUS852US852&um=1&ie=UTF-8&lr&q=related:jxzG3fISGRKjwM:scholar.google.com/). Early results suggest that using the Beta distribution admits a marginal increase in sample efficiency by restricting the agent model class to one which actually matches the acceptable output distribution, but doesn't have a huge payoff. Most continuous control benchmarks and research still use Gaussian distribution policies, for the simplicity of analysis, stable gradients, and easy implementation, which is why we keep this the default.

If you'd like to see Beta distribution policies in Garage (which would be the way to implement this behavior) you're welcome to send us a PR. We always love new contributions.

**Comment by ilinojkovic** [comment]
@ryanjulian, thanks for such a thorough answer!
