### ISSUE TITLE
TestOffPolicyVectorizedSampler is flaky

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#781]
See https://travis-ci.com/rlworkgroup/garage/jobs/214866746#L1705

**Comment by ryanjulian** [comment]
adding @naeioi and @ahtsan since @zequnyu might be away

**Comment by naeioi** [comment]
For the `imp` warning. This warning appears as long as tensorflow is imported in a test. There are other occurrences. for example, here https://travis-ci.com/rlworkgroup/garage/jobs/214866746#L1705.
When a script is run from command line rather than pytest, these warnings are somehow magically suppressed. I did some investigation but didn't find out how and why.

For the `inspect.getargspec()` warning. This is fixed in tf 1.13. See https://github.com/tensorflow/tensorflow/issues/16152.

To conclude, these warnings are rooted in tensorflow. Upgrading tensorflow may solve them. (But may also introduce other warnings!)
