### ISSUE TITLE
Replace `garage.spaces` with akro

### ISSUE THREAD

**Issue by eric-heiden** [rlworkgroup/garage#82]
Action and observation spaces of `garage`'s policies still rely on `garage.spaces`. We should get rid of that and use the counterparts from `gym.spaces` instead.

**Comment by ryanjulian** [comment]
I think this is preliminary.

I'd like to have as little code as possible too, but I don't think it will be clear what to do with Spaces until we rip out the Layers library, so I think we should wait for a design for that before attempting this.

In gym, spaces only represent input/output spaces for environments. In garage, spaces represent input/output spaces for environments *and* how to convert those spaces into neural network inputs/outputs *and* neural network subgraphs communicate *and* how training algorithms and samplers interface with neural network subgraphs.

For instance, the most important functionality in spaces right now is Space.new_tensor_variable(), which does not exist in gym.spaces. Yes, we can add a conversion function, and maybe that is what we'll eventually do, but wouldn't it be nice to instead have an interface that every NN library implements called `new_tensor_variable()` instead? That's what garage.spaces is. So perhaps this is an argument that garage.Space should inherit from gym.Space and add a few extra functions? Sounds like it could work, but I'm not sure, because it hasn't been designed. Etc.

**Comment by ryanjulian** [comment]
The above PR was a great improvement, but I don't think it really resolved Eric's concerns, so I'm reopening this.

**Comment by ryanjulian** [comment]
Fixed by #537
