### ISSUE TITLE
Make snapshot_config a required argument

### ISSUE THREAD

**Issue by zhanpenghe** [rlworkgroup/garage#853]
Currently, if we don't pass a `snapshot_config` to the runner like this (sorry, I am an old school garage user so I did not catch up with the snapshotter):
```
def run_task(*_):
    with LocalTFRunner() as runner:
```
the snapshots and log data could locate at different locations SILENTLY when we specify a log directory or log prefix.

I suggest that we should make this argument (i.e. the `snapshot_config` of a local runner) required so doing this will at least raise an error. Or, alternatively, I think we should handle this by forcing the snapshotter to use the log directory of dowel and remove the `snapshot_dir` from snapshotter. What do you think?

@krzentner @naeioi @ryanjulian @zequnyu

**Comment by ryanjulian** [comment]
This should either be required, or the default behavior should be sane. It should not locate the logs at different positions.

**Comment by zhanpenghe** [comment]
@ryanjulian I second this too.

**Comment by zequnyu** [comment]
I agree it is dangerous to have a silent bug: https://github.com/rlworkgroup/garage/pull/699#issuecomment-507883750.

It is interesting to force `snapshotter` to use `dower.logger` directory, since as I studied the source code, it's kind of hard to get `log_dir` from `logger`. For this, we might need to refactor logger's API? @zhanpenghe Also I think this way we need to think more about `snapshotter`'s default `log_dir` when we are not using experiment API (when doing tests).

Alternatively as you pointed out, we can make `config` required for Runner, and add a temporary `config` to test fixtures for the use of every test.

It's hard to foresee which one is better, but I can try both to figure out.

**Comment by zequnyu** [comment]
Close by #860.
