### ISSUE TITLE
Remove n_epoch_cycles from the codebase.

### ISSUE THREAD

**Issue by zequnyu** [rlworkgroup/garage#948]
After some discussion with KR and Keren, we aim to remove `n_epoch_cycles` completely from the codebase.

The steps:

1. delete `n_epoch_cycles` from both Algorithms and Runner
2. multiply the number of epochs by the old `n_epoch_cycles` values in the examples
3. rewrite the cem and cma-es train() loops using `n_samples` to iterate
4. possibly refactor Runner accordingly

Please feel free to add your thought and comments below.

**Comment by ryanjulian** [comment]
This sounds great. I look forward to reviewing it.

Will DQN and/or DDPG retain some hyperparameter similar to n_epoch_cycles?

**Comment by naeioi** [comment]
@zequnyu Regarding your 3rd step. If epoches is replaced with `epoch * n_epoch_cycles`, the benchmark will give a result significantly different to baselines. I believe the right way to do this is to replace `n_epoch_cycles` with a new `steps_per_epoch` in DDPG and TD3.

I want to add some context and break this into several tasks. 

**What is `n_epoch_cycles`?**
It is defined as the number of batches per epoch. In other words, `sampler.obtain_samples()` is called this many times per epoch.

The policy update has nothing to do with `n_epoch_cycles`. The policy may get updated more than once per cycle (e.g. DDPG), or once per cycle (All on-policy algos), or not updated until an epoch is about to finished (e.g. CEM). 

**It was not in rllab, then why is it added to garage?**
The only reason is that openai baselines uses it in DDPG (only in DDPG) and we are doing benchmark against baselines. 

rlkit has a similar parameter which they call it `num_train_loops_per_epoch`, and they are using it so that both on- and off- algorithms fits into a single trainer (equiv. of runner) interface - This is how we proceed before #728 when the training loop is owned by the runner. 

This design, the design that the runner owns the training loop, it works perfect for on-policy, acceptable for off-policy and awkward for others algorithms e.g. with those with many policies. KR and I have some discussion in #704.

**Why are we removing it?**
The reasons are manifold. But I think mostly because it makes parameter tunning tricky.

- This parameter is not in the paper, but just implementation detail inherited from DDPG in baselines. 
- The runner owns `n_epoch_cycles`, but it is not used in the runner any more.
- Number of environment steps per epoch is a important parameter. But how to compute it is confusing.

**How are we removing it?**
The runner accepts `n_epoch_cycles` but uses it in nowhere so just delete it. 

For algorithms, there are three types of algorithms using it 
- Evolution strategy algorithms (CEM, CMAES)
  - [ ] Update `n_samples` of polices in `train()`.
- Off-policy algorithms (DDPG, TD3)
  - [ ] Replace `n_epoch_cycles` with `steps_per_epoch`, or just use `batch_size`. 
- Q-learning algorithm (DQN, DDQN)
  - [ ] Same as off-policy algorithm.

**Comment by ryanjulian** [comment]
@krzentner and @zequnyu 

Thanks for the excellent summary. You both have done a great job, and I want to make sure you know I appreciate your work on this, even though we've gone through several attempts at fixing this wort in the API.

I think what you describe is definitely an improvement over the status quo. Speaking as a maintainer, all I ask is that these hyperparameters be named consistently and very well-documented.

**Comment by zequnyu** [comment]
Closed by #1093.
